### DISCUSSION TITLE
media queries in props

### DISCUSSION THREAD

**Discussion by j-waaang** [pmndrs/react-spring#1554] [Support]
I want to have different animations on mobile and desktop. It's possible to get it to work with a media query hook but that won't work on a project with server-side-rendering. So I am looking for a solution to use media-queries inside the spring props. Anyone can help me?

Sol 1 (works but not good for SSR)
```
const isDesktop = useDesktop() // won't work for SSR

const style = useSpring({
    to: {
      transform: `translate(0px, ${isDesktop ? 50 : 30} px)`,
    },
  })
```

Sol 2 (would be nice to get something like this to work)

```const style = useSpring({
    to: {
      transform: `translate(0px, 30px)`,
      ["@media screen and (min-width: 768px)"]: {
        transform: `translate(0px, 50px)`,
      },
    },
  })
```

**Comment by DamianPereira** [comment]
Maybe this can be solved with css custom properties. I have not tried it, but maybe something like this:

js code:
```javascript
const style = useSpring({
    to: {
      transform: `translate(0px, var(--animation-vertical-offset))`,
    },
  })
```
styles
```css
:root {
  --animation-vertical-offset: 30px;
}
@media screen and (min-width: 768px) {
  :root {
    --animation-vertical-offset: 50px;
  }
}
```
