### DISCUSSION TITLE
Change two CSS properties of two components

### DISCUSSION THREAD

**Discussion by strarsis** [pmndrs/react-spring#1858] [Support]
For achieving an item sliding out effect (iOS-style) for a complicated table DOM, the whole table row has to be moved on the X-Axis (this already works nicely and easily with react-spring) - but the most outside column has to change in width - by the same amount.

CSS example:
```css
tr {
  transform: translateX(<mx>px ... default react-spring stuff - works great already);
}

td.shelf {
  position: absolute;
  top: 0;
  bottom: 0;

  width: <mx>px; /* this should be changed instead of transform */
}
````
Both components have `style` props. Instead of using the default `transform` approach, 
the `width` property of component 2 should  be changed instead.

As already an elegant `bind` approach is used - can the `x` in `styles` be changed to `width`?
