### ISSUE TITLE
Add react as peer dependency for 'react-spring v9'

### ISSUE THREAD

**Issue by joomation** [pmndrs/react-spring#1577]
## 🐛 Bug Report
This Issues the missing react peer dependency on the @react-spring/animated, @react-spring/web,..
Install the entire react-spring library, when using

```tsx
import { useSpring } from 'react-spring';
```

yarn v2 will refuse giving access to the dependencies.

```
$ yarn build
Module not found: @react-spring/animated tried to access react (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
Module not found: @react-spring/web tried to access react (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
```
## To Reproduce
When installing full react-spring library, a peer dependency not found to access `react`, `react-dom`

## Expected behavior

In the `react-spring` package, peerDeps also be declared as follows.
https://github.com/pmndrs/react-spring/blob/v9.2.3/packages/react-spring/package.json

```json
"peerDependencies": {
   "react": "^16.8.0  || ^17.0.0", 
   "react-dom": "^16.8.0  || ^17.0.0"  
}
```

## Environment

- `react-spring` v9.2.x
- `react` v16.8.x

**Comment by joshuaellis** [comment]
Please follow the template and include a reproduction of the issue.

**Comment by joshuaellis** [comment]
closing due to inactivity

**Comment by lensbart** [comment]
@joshuaellis this is still an issue. Please confirm that all packages list any dependencies they use in their `package.json`.

As for a reproduction, it suffices to use `react-spring` in any repository that uses [Yarn](https://yarnpkg.com) as a package manager. Note that Yarn is a bit more strict about dependencies requirements, but that these rules are not Yarn-specific (i.e. are general best practices).

I get the following errors:

```
@react-spring/animated tried to access react (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
@react-spring/core tried to access react (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
@react-spring/shared tried to access react (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
@react-spring/web tried to access react-dom (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
```

These errors can be ignored by putting the following in `.yarnrc.yml`:

```
packageExtensions:
  # awaiting fix: https://github.com/pmndrs/react-spring/issues/1577
  '@react-spring/animated@*':
    peerDependenciesMeta:
      react:
        optional: true
  '@react-spring/core@*':
    peerDependenciesMeta:
      react:
        optional: true
  '@react-spring/shared@*':
    peerDependenciesMeta:
      react:
        optional: true
  '@react-spring/web@*':
    peerDependenciesMeta:
      react-dom:
        optional: true
```
